---
title: "Data Clean"
output: html_notebook
---

This part contains the data cleaning part of capstone project, which is supervised by Prof. Jerzy.

# Data clean process for CRSP
```{r}
# In this part, we input the CRSP quarterly data and reform them into features.
csrp_ori <- readxl::read_excel("D:\\data\\Capstone\\Data\\CRSP_Quarterly_data.xlsx")

csrp_feature <- subset(csrp_ori, select = c(gvkey, datadate, fyearq, fqtr))

csrp_feature$mv <- csrp_ori$cshoq * csrp_ori$prccq

csrp_feature$ev <- csrp_feature$mv + csrp_ori$dlcq + csrp_ori$dlttq + csrp_ori$pstkq - csrp_ori$cheq

csrp_feature$tax_rate <- csrp_ori$txtq / csrp_ori$piq

csrp_ori$cfo <- c(NA, diff(csrp_ori$oancfy, lag = 1))
csrp_feature$cfo2ev <- csrp_ori$cfo + (csrp_ori$xintq * (1 - csrp_feature$tax_rate))

csrp_ori$assets <- csrp_ori$ceqq + csrp_ori$dlcq + csrp_ori$dlttq + csrp_ori$pstkq - csrp_ori$cheq
csrp_feature$rona <- (csrp_ori$ibq + (csrp_ori$xintq * (1 - csrp_feature$tax_rate))) / csrp_ori$assets

csrp_ori$ebitda <- csrp_ori$saleq - csrp_ori$cogsq - csrp_ori$xsgaq
csrp_feature$ebitda2ev <- csrp_ori$ebitda / csrp_feature$ev

csrp_feature$e2pfy0 <- csrp_ori$ibcomq / csrp_feature$mv

csrp_feature$bb2p <- (csrp_ori$dvy + csrp_ori$prstkcy - csrp_ori$sstky) / csrp_feature$mv

csrp_ori$eq_repo <- csrp_ori$prstkcy - csrp_ori$sstky
csrp_ori$debt_repo <- csrp_ori$dltry - csrp_ori$dlcchy - csrp_ori$dltisy
csrp_feature$bb2ev <- (csrp_ori$dvy + csrp_ori$eq_repo - csrp_ori$debt_repo) / csrp_feature$ev

csrp_feature$b2p <- csrp_ori$ceqq / csrp_feature$mv

csrp_feature$s2ev <- csrp_ori$saleq / csrp_feature$ev

csrp_feature$dvy <- csrp_ori$dvy

csrp_feature$date <- TransYQtoDate(csrp_feature$fyearq, csrp_feature$fqtr)

# We save the features thus we don't need to recalculate it everytime.
writexl::write_xlsx(csrp_feature, path = "D:\\data\\Capstone\\Data\\CRSP_Features.xlsx", col_names = TRUE)
```

# Data clean process for OHLC
```{r}
# Now we prepare the OHLC prices for these stocks.
ohlc_ori <- readxl::read_excel("D:\\data\\Capstone\\Data\\OHLCV_v1.xlsx")
temp <- as.character(ohlc_ori$date)
ohlc_ori$month <- as.numeric(substr(temp, start = 5, stop = 6))
ohlc_ori$day <- as.numeric(substr(temp, start = 7, stop = 8))

ohlc_v1 <- subset(ohlc_ori, (ohlc_ori$month %in% c(3, 6, 9, 12)) & (ohlc_ori$day >= 28))

# Now we wish to pick out the last valid record in 3,6,9,12 month.
ohlc_v1$ym <- substr(as.character(ohlc_v1$date), start = 1, stop = 6)

ohlc_final <- ohlc_v1 %>%
  group_by(permno) %>%
  group_by(ym) %>%
  top_n(-1, day)

ohlc_final <- ohlc_final %>%
  group_by(gvkey) %>%
  mutate(ret = (c(close[-(seq(1))], rep(NA, 1)) / close - 1))

# We save the results thus we don't need to recalculate it everytime.
writexl::write_xlsx(ohlc_final, path = "D:\\data\\Capstone\\Data\\OHLC_quarter.xlsx", col_names = TRUE)
```
# Data clean process for LinkKey
```{r}
link_key <- readxl::read_excel("D:\\data\\Capstone\\Data\\LinkKey_v2.xlsx")
lk_v1 <- distinct(subset(link_key, select = c(gvkey, tic, cusip, lpermno)))
names(lk_v1)[names(lk_v1) == "lpermno"] <- "permno"
# We save the results thus we don't need to recalculate it everytime.
writexl::write_xlsx(LK_v1, path = "D:\\data\\Capstone\\Data\\LK.xlsx", col_names = TRUE)
```
